/**
 * Neighborhood data for SEO landing pages.
 * Each entry generates a page at /[locale]/neighborhoods/[slug]
 *
 * To add a new neighborhood: copy any object below, change slug, update content.
 * Both `en` and `pt` blocks are required.
 */

export const neighborhoods = [
  {
    slug: 'alfama',
    region: 'central',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1600&q=80',
    en: {
      name: 'Alfama',
      title: 'Removals in Alfama, Lisbon',
      metaTitle: 'Removals & House Movers in Alfama, Lisbon | Removals Lisbon',
      metaDescription: 'Specialist removal company for Alfama, Lisbon. We handle the narrow streets, steep stairs, and parking challenges of Lisbon\'s oldest neighbourhood. Get a free quote.',
      intro: 'Alfama is the most beautiful and most challenging neighbourhood in Lisbon to move into or out of. Cobbled lanes barely wide enough for a scooter, four and five-storey buildings without lifts, and parking restrictions that change by the hour — moving here demands a team that knows the area.',
      challenges: [
        'Narrow medieval streets where standard removal vans simply cannot fit',
        'Most buildings predate the lift, meaning everything goes up by hand',
        'Tight loading windows due to tram routes and tourist foot traffic',
        'Restricted parking with permit requirements in much of the historic centre',
      ],
      ourApproach: 'We use smaller transit-style vans that navigate Alfama\'s lanes, plus stair-trolleys and shoulder straps for safe handling on the steep climbs. Our team scouts your address in advance and coordinates with the parish council for parking when needed. We\'ve moved residents in and out of Alfama hundreds of times — every nuance of the neighbourhood is in our playbook.',
      services: 'Full house and apartment removals, single-item collections (sofas, beds, fridges), furniture disposal, and post-renovation clearance.',
      keywords: 'removals Alfama, movers Alfama Lisbon, house movers Alfama, apartment movers Alfama, Alfama moving company',
    },
    pt: {
      name: 'Alfama',
      title: 'Mudanças em Alfama, Lisboa',
      metaTitle: 'Mudanças e Transportes em Alfama, Lisboa | Removals Lisbon',
      metaDescription: 'Empresa especializada em mudanças em Alfama, Lisboa. Conhecemos as ruas estreitas, escadarias íngremes e desafios de estacionamento do bairro mais antigo de Lisboa. Peça orçamento.',
      intro: 'Alfama é o bairro mais bonito e mais desafiante de Lisboa para se fazer uma mudança. Ruas calcetadas estreitíssimas, edifícios de quatro e cinco andares sem elevador, e restrições de estacionamento que mudam à hora — mudar-se aqui exige uma equipa que conhece a zona.',
      challenges: [
        'Ruas medievais estreitas onde carrinhas de mudanças padrão não passam',
        'A maioria dos edifícios é anterior ao elevador, ou seja, tudo sobe à mão',
        'Janelas de carga apertadas devido aos elétricos e ao trânsito turístico',
        'Estacionamento restrito com necessidade de licença em grande parte do centro histórico',
      ],
      ourApproach: 'Usamos carrinhas mais pequenas (tipo "transit") que percorrem as vielas de Alfama, mais carrinhos de escada e cintas de ombro para um manuseamento seguro nas subidas. A nossa equipa visita a sua morada antes da mudança e coordena com a Junta de Freguesia para o estacionamento quando necessário. Já fizemos centenas de mudanças em Alfama — todas as nuances do bairro estão no nosso manual.',
      services: 'Mudanças completas de casa e apartamento, recolhas de itens individuais (sofás, camas, frigoríficos), remoção de mobiliário e limpeza pós-obra.',
      keywords: 'mudanças Alfama, transportes Alfama, mudanças de casa Alfama, mudanças apartamento Alfama, empresa mudanças Alfama',
    },
  },
  {
    slug: 'bairro-alto',
    region: 'central',
    image: 'https://images.unsplash.com/photo-1588535208166-b78c4ad11bd9?w=1600&q=80',
    en: {
      name: 'Bairro Alto',
      title: 'Removals in Bairro Alto, Lisbon',
      metaTitle: 'Removals & House Movers in Bairro Alto, Lisbon | Removals Lisbon',
      metaDescription: 'Professional removals in Bairro Alto, Lisbon. We work around the nightlife, narrow streets, and walk-up apartments unique to this lively neighbourhood. Free quotes.',
      intro: 'Bairro Alto is one of the most desirable places to live in central Lisbon — and one of the trickiest to move into. The neighbourhood transforms each evening into a nightlife hotspot, which means moves need to be carefully timed around bar deliveries, foot traffic, and street cleaning.',
      challenges: [
        'Narrow grid streets shared with bars, restaurants, and pedestrian crowds',
        'Most apartments are 3rd–5th floor walk-ups in 18th-century buildings',
        'Daily street cleaning means restricted access in early mornings',
        'Limited daytime parking with strict residential permit zones',
      ],
      ourApproach: 'We schedule Bairro Alto moves for early morning windows, before the bars start their deliveries and after the street cleaners pass. Our team is experienced with the neighbourhood\'s typical staircases — narrow, winding, with low ceilings — and we use specialist equipment to safely move large items through tight turns.',
      services: 'Full apartment removals, studio and one-bed moves, furniture and appliance collections, post-tenancy clearance for landlords.',
      keywords: 'removals Bairro Alto, movers Bairro Alto Lisbon, Bairro Alto moving company, apartment movers Bairro Alto',
    },
    pt: {
      name: 'Bairro Alto',
      title: 'Mudanças no Bairro Alto, Lisboa',
      metaTitle: 'Mudanças e Transportes no Bairro Alto, Lisboa | Removals Lisbon',
      metaDescription: 'Mudanças profissionais no Bairro Alto, Lisboa. Trabalhamos em torno da vida noturna, ruas estreitas e apartamentos sem elevador deste bairro animado. Orçamentos grátis.',
      intro: 'O Bairro Alto é um dos sítios mais desejados para viver no centro de Lisboa — e um dos mais complicados para mudanças. O bairro transforma-se a cada noite num ponto de vida noturna, o que significa que as mudanças têm de ser cuidadosamente programadas entre entregas de bares, peões e limpeza das ruas.',
      challenges: [
        'Ruas estreitas em grelha partilhadas com bares, restaurantes e peões',
        'A maioria dos apartamentos são 3.º a 5.º andar sem elevador em edifícios do século XVIII',
        'Limpeza diária das ruas restringe o acesso de madrugada',
        'Estacionamento diurno limitado com zonas de licença residencial rigorosas',
      ],
      ourApproach: 'Agendamos mudanças no Bairro Alto para janelas de madrugada, antes das entregas dos bares e depois da passagem da limpeza. A nossa equipa conhece bem as escadarias típicas do bairro — estreitas, em caracol, com tetos baixos — e usamos equipamento especializado para mover itens grandes em curvas apertadas com segurança.',
      services: 'Mudanças completas de apartamentos, mudanças de estúdios e T1, recolhas de mobiliário e eletrodomésticos, limpeza pós-arrendamento para senhorios.',
      keywords: 'mudanças Bairro Alto, transportes Bairro Alto, empresa mudanças Bairro Alto, mudanças apartamento Bairro Alto',
    },
  },
  {
    slug: 'chiado',
    region: 'central',
    image: 'https://images.unsplash.com/photo-1518730518541-d0843268c287?w=1600&q=80',
    en: {
      name: 'Chiado',
      title: 'Removals in Chiado, Lisbon',
      metaTitle: 'Removals & House Movers in Chiado, Lisbon | Removals Lisbon',
      metaDescription: 'Specialist removal services for Chiado, Lisbon. From classic apartments above the boutiques to modern penthouses, we handle every type of Chiado move. Free quote.',
      intro: 'Chiado sits between Bairro Alto and Baixa, and is home to some of the most beautiful — and most expensive — apartments in Lisbon. Many sit above ground-floor boutiques, which means moving in or out has to fit around shop opening hours and pedestrian traffic on Rua Garrett.',
      challenges: [
        'Pedestrianised main streets restrict vehicle access during the day',
        'Apartments above commercial premises require careful coordination',
        'High-value items and antiques common in Chiado homes',
        'Tight historic stairwells in many buildings',
      ],
      ourApproach: 'We coordinate with shop owners and the parish council to find loading windows that don\'t disrupt either side. Our team is fully insured and experienced with high-value items — antique furniture, fine art, and the kind of pieces Chiado residents tend to own. We provide proper packing materials, climate-aware transport, and white-glove handling as standard.',
      services: 'Premium house and apartment removals, art and antique handling, single-item white-glove deliveries, packing and unpacking services.',
      keywords: 'removals Chiado, movers Chiado Lisbon, Chiado moving company, premium movers Lisbon, antique movers Lisbon',
    },
    pt: {
      name: 'Chiado',
      title: 'Mudanças no Chiado, Lisboa',
      metaTitle: 'Mudanças e Transportes no Chiado, Lisboa | Removals Lisbon',
      metaDescription: 'Serviços especializados de mudanças para o Chiado, Lisboa. De apartamentos clássicos acima das boutiques a coberturas modernas, tratamos de cada tipo de mudança. Orçamento grátis.',
      intro: 'O Chiado fica entre o Bairro Alto e a Baixa, e alberga alguns dos apartamentos mais bonitos — e mais caros — de Lisboa. Muitos ficam acima de boutiques no rés-do-chão, o que significa que as mudanças têm de se encaixar nos horários das lojas e no trânsito pedonal da Rua Garrett.',
      challenges: [
        'Ruas pedonais principais restringem o acesso a veículos durante o dia',
        'Apartamentos acima de espaços comerciais exigem coordenação cuidadosa',
        'Itens de alto valor e antiguidades comuns nas casas do Chiado',
        'Escadas históricas apertadas em muitos edifícios',
      ],
      ourApproach: 'Coordenamos com lojistas e Junta de Freguesia para encontrar janelas de carga que não perturbem nenhum dos lados. A nossa equipa está totalmente segurada e tem experiência com itens de alto valor — mobiliário antigo, arte, peças que os residentes do Chiado costumam ter. Fornecemos materiais de embalagem adequados, transporte com controlo climático e manuseamento "luva branca" como padrão.',
      services: 'Mudanças premium de casa e apartamento, manuseamento de arte e antiguidades, entregas individuais "luva branca", serviços de embalagem e desembalagem.',
      keywords: 'mudanças Chiado, transportes Chiado, empresa mudanças Chiado, mudanças premium Lisboa, mudanças antiguidades Lisboa',
    },
  },
  {
    slug: 'principe-real',
    region: 'central',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600&q=80',
    en: {
      name: 'Príncipe Real',
      title: 'Removals in Príncipe Real, Lisbon',
      metaTitle: 'Removals & House Movers in Príncipe Real, Lisbon | Removals Lisbon',
      metaDescription: 'Professional removals in Príncipe Real, Lisbon. We move families and professionals into and out of this elegant central neighbourhood. Free quotes.',
      intro: 'Príncipe Real has become Lisbon\'s most fashionable inner-city neighbourhood — full of design shops, leafy squares, and restored 19th-century palacetes converted into apartments. Moves here often involve substantial homes with valuable contents.',
      challenges: [
        'Large period apartments with substantial volumes to move',
        'High ceilings and grand staircases that need specialist handling',
        'Limited parking around the central garden and cafés',
        'Many buildings without lifts, despite the size of the apartments',
      ],
      ourApproach: 'Príncipe Real moves usually take a full team and a half or full day. We provide a detailed plan in advance — including parking permits, packing crews, and protective floor coverings for the often-original wooden floors. For larger families, we offer a full pack-and-unpack service so you don\'t lift a finger.',
      services: 'Family home removals, executive relocations, full-service packing, art and instrument transport, storage solutions.',
      keywords: 'removals Príncipe Real, movers Príncipe Real Lisbon, family movers Lisbon, Príncipe Real moving company',
    },
    pt: {
      name: 'Príncipe Real',
      title: 'Mudanças no Príncipe Real, Lisboa',
      metaTitle: 'Mudanças e Transportes no Príncipe Real, Lisboa | Removals Lisbon',
      metaDescription: 'Mudanças profissionais no Príncipe Real, Lisboa. Mudamos famílias e profissionais de e para este elegante bairro central. Orçamentos grátis.',
      intro: 'O Príncipe Real tornou-se o bairro mais fashionable do centro de Lisboa — cheio de lojas de design, praças arborizadas e palacetes do século XIX restaurados e convertidos em apartamentos. As mudanças aqui envolvem frequentemente casas grandes com conteúdos valiosos.',
      challenges: [
        'Apartamentos antigos grandes com volumes substanciais para mover',
        'Tetos altos e escadarias imponentes que exigem manuseamento especializado',
        'Estacionamento limitado em torno do jardim central e cafés',
        'Muitos edifícios sem elevador, apesar do tamanho dos apartamentos',
      ],
      ourApproach: 'As mudanças no Príncipe Real costumam exigir uma equipa completa e meio dia ou um dia inteiro. Fornecemos um plano detalhado com antecedência — incluindo licenças de estacionamento, equipas de embalagem e proteções para os pisos de madeira frequentemente originais. Para famílias maiores, oferecemos um serviço completo de embalar e desembalar para que não tenha de mexer um dedo.',
      services: 'Mudanças de casas familiares, relocações executivas, embalagem completa, transporte de arte e instrumentos, soluções de armazenamento.',
      keywords: 'mudanças Príncipe Real, transportes Príncipe Real, mudanças famílias Lisboa, empresa mudanças Príncipe Real',
    },
  },
  {
    slug: 'graca',
    region: 'central',
    image: 'https://images.unsplash.com/photo-1531219572328-a0171b4448a3?w=1600&q=80',
    en: {
      name: 'Graça',
      title: 'Removals in Graça, Lisbon',
      metaTitle: 'Removals & House Movers in Graça, Lisbon | Removals Lisbon',
      metaDescription: 'Friendly, affordable removals in Graça, Lisbon. We know the steep streets, the trams, and the practicalities of moving in this hilltop neighbourhood. Free quote.',
      intro: 'Graça sits high above the city, with miradouros giving some of the best views in Lisbon. It\'s a residential neighbourhood with a strong local character — and steep, twisting streets that the famous 28 tram navigates daily. Moves here mean working with the tram timetable, the gradient, and a community that knows itself.',
      challenges: [
        'Steep streets that test even the best-equipped removal team',
        'Tram routes (28 in particular) restrict large vehicles',
        'Staircases inside Graça buildings are often steep and narrow',
        'Limited turning space at the top of many streets',
      ],
      ourApproach: 'We use lighter, more agile vans for Graça moves and time the loading carefully around tram schedules. Our team is fit, experienced with stairs, and we always send enough crew to do the job in good time without leaving items in the truck unnecessarily.',
      services: 'Apartment moves, single-item collections, furniture disposal, IKEA delivery and assembly.',
      keywords: 'removals Graça, movers Graça Lisbon, Graça moving company, apartment movers Graça',
    },
    pt: {
      name: 'Graça',
      title: 'Mudanças na Graça, Lisboa',
      metaTitle: 'Mudanças e Transportes na Graça, Lisboa | Removals Lisbon',
      metaDescription: 'Mudanças simpáticas e acessíveis na Graça, Lisboa. Conhecemos as ladeiras, os elétricos e a praticalidade de uma mudança neste bairro alto. Orçamento grátis.',
      intro: 'A Graça fica no alto da cidade, com miradouros que dão algumas das melhores vistas de Lisboa. É um bairro residencial com forte carácter local — e ruas íngremes e sinuosas que o famoso elétrico 28 percorre diariamente. As mudanças aqui significam trabalhar com o horário do elétrico, com o declive, e com uma comunidade que se conhece.',
      challenges: [
        'Ladeiras íngremes que testam até a melhor equipa de mudanças',
        'Linhas de elétrico (em particular o 28) restringem veículos grandes',
        'As escadas dos edifícios da Graça são muitas vezes íngremes e estreitas',
        'Espaço limitado para inverter no topo de muitas ruas',
      ],
      ourApproach: 'Usamos carrinhas mais leves e ágeis para mudanças na Graça e cronometramos o carregamento em torno do horário dos elétricos. A nossa equipa está em forma, é experiente com escadas, e enviamos sempre equipa suficiente para fazer o trabalho a tempo sem deixar itens na carrinha desnecessariamente.',
      services: 'Mudanças de apartamento, recolhas individuais, remoção de mobiliário, entrega e montagem IKEA.',
      keywords: 'mudanças Graça, transportes Graça, empresa mudanças Graça, mudanças apartamento Graça',
    },
  },
  {
    slug: 'mouraria',
    region: 'central',
    image: 'https://images.unsplash.com/photo-1573486569320-dde892eb6716?w=1600&q=80',
    en: {
      name: 'Mouraria',
      title: 'Removals in Mouraria, Lisbon',
      metaTitle: 'Removals & House Movers in Mouraria, Lisbon | Removals Lisbon',
      metaDescription: 'Reliable removal services for Mouraria, Lisbon. We understand the labyrinth of streets, multicultural community, and walk-up apartments unique to this historic neighbourhood.',
      intro: 'Mouraria is one of the most authentic and multicultural neighbourhoods in Lisbon — birthplace of fado, home to communities from across the world, and a maze of streets too narrow for most vehicles. Moving here requires a team that respects both the practical and the cultural texture of the place.',
      challenges: [
        'A genuine labyrinth of pedestrianised lanes and stairs',
        'Buildings often have multiple narrow stairwells',
        'Limited vehicle access — much loading is done from a distance',
        'Tight parking near the Largo do Intendente',
      ],
      ourApproach: 'We use small vans and porters for Mouraria moves — sometimes covering up to 100m on foot between vehicle and apartment. We always send extra crew so that the load doesn\'t take all day, and we work hard to be quiet, respectful neighbours during the move.',
      services: 'Apartment moves, single-item deliveries, post-renovation clearance, junk and unwanted furniture removal.',
      keywords: 'removals Mouraria, movers Mouraria Lisbon, Mouraria moving company, apartment movers Mouraria',
    },
    pt: {
      name: 'Mouraria',
      title: 'Mudanças na Mouraria, Lisboa',
      metaTitle: 'Mudanças e Transportes na Mouraria, Lisboa | Removals Lisbon',
      metaDescription: 'Serviços de mudanças fiáveis para a Mouraria, Lisboa. Conhecemos o labirinto de ruas, a comunidade multicultural e os apartamentos sem elevador deste bairro histórico.',
      intro: 'A Mouraria é um dos bairros mais autênticos e multiculturais de Lisboa — berço do fado, casa de comunidades de todo o mundo, e um labirinto de ruas demasiado estreitas para a maioria dos veículos. Mudar-se aqui exige uma equipa que respeite tanto a textura prática como a cultural do lugar.',
      challenges: [
        'Um verdadeiro labirinto de vielas pedonais e escadas',
        'Os edifícios têm muitas vezes várias escadas estreitas',
        'Acesso limitado a veículos — grande parte da carga é feita à distância',
        'Estacionamento apertado junto ao Largo do Intendente',
      ],
      ourApproach: 'Usamos carrinhas pequenas e carregadores para mudanças na Mouraria — por vezes percorrendo até 100m a pé entre o veículo e o apartamento. Enviamos sempre equipa extra para que a carga não demore todo o dia, e esforçamo-nos por ser vizinhos discretos e respeitosos durante a mudança.',
      services: 'Mudanças de apartamento, entregas individuais, limpeza pós-obra, remoção de entulho e mobiliário indesejado.',
      keywords: 'mudanças Mouraria, transportes Mouraria, empresa mudanças Mouraria, mudanças apartamento Mouraria',
    },
  },
  {
    slug: 'cascais',
    region: 'greater',
    image: 'https://images.unsplash.com/photo-1626622437527-b9b25cc6e164?w=1600&q=80',
    en: {
      name: 'Cascais',
      title: 'Removals in Cascais',
      metaTitle: 'Removals & House Movers in Cascais | Removals Lisbon',
      metaDescription: 'Professional removals in Cascais. Family homes, expat moves, and beachside relocations across Cascais, Estoril, Carcavelos, and the Lisbon Riviera. Free quote.',
      intro: 'Cascais is the heart of the Lisbon Riviera — beachside villas, expat families, and a high concentration of professionals working in Lisbon but living by the sea. Moves here are typically larger homes with more contents, and we run regular routes between Cascais and central Lisbon.',
      challenges: [
        'Larger family homes mean larger loads and longer days',
        'Beach humidity affects how items need to be packed and transported',
        'Some properties have long driveways and steep access',
        'Coordinating between Cascais and Lisbon when moves involve both',
      ],
      ourApproach: 'We send full crews for Cascais moves — typically 3-4 movers and a full-size truck. For expat families relocating from Cascais to other parts of Portugal or abroad, we offer end-to-end packing, transport, and storage. We know the gated communities, the access codes, and the practicalities of moving from this part of the coast.',
      services: 'Family home removals, villa moves, expat relocations, packing services, storage and consolidation.',
      keywords: 'removals Cascais, movers Cascais, Cascais moving company, expat movers Cascais, Lisbon to Cascais removals',
    },
    pt: {
      name: 'Cascais',
      title: 'Mudanças em Cascais',
      metaTitle: 'Mudanças e Transportes em Cascais | Removals Lisbon',
      metaDescription: 'Mudanças profissionais em Cascais. Casas familiares, mudanças de expatriados e relocações junto à praia em Cascais, Estoril, Carcavelos e na Linha de Cascais.',
      intro: 'Cascais é o coração da Linha — moradias junto à praia, famílias expatriadas, e uma alta concentração de profissionais que trabalham em Lisboa mas vivem junto ao mar. As mudanças aqui costumam ser de casas maiores com mais conteúdos, e mantemos rotas regulares entre Cascais e o centro de Lisboa.',
      challenges: [
        'Casas familiares maiores significam cargas maiores e dias mais longos',
        'A humidade da costa afeta a forma como os itens devem ser embalados e transportados',
        'Algumas propriedades têm acessos longos e íngremes',
        'Coordenar entre Cascais e Lisboa quando a mudança envolve ambos',
      ],
      ourApproach: 'Enviamos equipas completas para mudanças em Cascais — tipicamente 3-4 carregadores e uma carrinha de grande dimensão. Para famílias expatriadas a mudar-se de Cascais para outras partes de Portugal ou para o estrangeiro, oferecemos embalagem, transporte e armazenamento de fim a fim. Conhecemos os condomínios fechados, os códigos de acesso, e a praticalidade de uma mudança nesta zona da costa.',
      services: 'Mudanças de casas familiares, mudanças de moradias, relocações de expatriados, serviços de embalagem, armazenamento.',
      keywords: 'mudanças Cascais, transportes Cascais, empresa mudanças Cascais, mudanças expatriados Cascais, Lisboa para Cascais',
    },
  },
  {
    slug: 'estoril',
    region: 'greater',
    image: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=1600&q=80',
    en: {
      name: 'Estoril',
      title: 'Removals in Estoril',
      metaTitle: 'Removals & House Movers in Estoril | Removals Lisbon',
      metaDescription: 'Specialist removal services for Estoril. Coastal villas, apartment moves, and seamless relocations along the Lisbon Riviera. Free quote.',
      intro: 'Estoril sits between Cascais and the rest of the Lisbon Riviera, known for its grand villas, casino, and palm-lined seafront. Moves here range from small apartment relocations to substantial multi-day villa moves, and our team handles both with the same care.',
      challenges: [
        'A mix of property types from small studios to grand villas',
        'Some streets close to the seafront have access restrictions in summer',
        'High-end furnishings and art common in Estoril homes',
      ],
      ourApproach: 'We treat every Estoril move with care, regardless of size. Larger villas get a full crew with packing materials, floor protection, and a dedicated coordinator. Smaller apartment moves get our nimble two-person crew. Either way, we\'re punctual, careful, and bilingual.',
      services: 'Villa and apartment removals, art and antique handling, packing services, storage.',
      keywords: 'removals Estoril, movers Estoril, Estoril moving company, villa movers Estoril',
    },
    pt: {
      name: 'Estoril',
      title: 'Mudanças no Estoril',
      metaTitle: 'Mudanças e Transportes no Estoril | Removals Lisbon',
      metaDescription: 'Serviços especializados de mudanças para o Estoril. Moradias junto à costa, mudanças de apartamento e relocações sem complicações na Linha de Cascais.',
      intro: 'O Estoril fica entre Cascais e o resto da Linha, conhecido pelas suas grandes moradias, casino e marginal com palmeiras. As mudanças aqui vão desde pequenas relocações de apartamento a mudanças substanciais de moradias de vários dias, e a nossa equipa trata ambos com o mesmo cuidado.',
      challenges: [
        'Uma mistura de tipos de propriedade, desde pequenos estúdios a grandes moradias',
        'Algumas ruas perto da marginal têm restrições de acesso no verão',
        'Mobiliário e arte de alta gama comuns nas casas do Estoril',
      ],
      ourApproach: 'Tratamos cada mudança no Estoril com cuidado, independentemente do tamanho. Moradias maiores recebem uma equipa completa com materiais de embalagem, proteção de pisos e um coordenador dedicado. Mudanças mais pequenas recebem a nossa equipa ágil de duas pessoas. De qualquer forma, somos pontuais, cuidadosos e bilingues.',
      services: 'Mudanças de moradias e apartamentos, manuseamento de arte e antiguidades, serviços de embalagem, armazenamento.',
      keywords: 'mudanças Estoril, transportes Estoril, empresa mudanças Estoril, mudanças moradia Estoril',
    },
  },
  {
    slug: 'sintra',
    region: 'greater',
    image: 'https://images.unsplash.com/photo-1564555484700-ddc0ff8e9f0a?w=1600&q=80',
    en: {
      name: 'Sintra',
      title: 'Removals in Sintra',
      metaTitle: 'Removals & House Movers in Sintra | Removals Lisbon',
      metaDescription: 'Professional removals in Sintra. We move families and professionals between Sintra and Lisbon, plus relocations within the Sintra hills. Free quote.',
      intro: 'Sintra is fairy-tale Portugal — castles, hills, mist, and a mix of historic estates and modern villas. The combination of winding mountain roads, narrow village streets, and properties tucked into the forest makes for moves that always need a careful plan.',
      challenges: [
        'Winding mountain roads add transit time and require careful driving',
        'Some properties only accessible by single-track forest roads',
        'Sintra weather (mist, rain) affects load timing',
        'Historic village centres have tight access',
      ],
      ourApproach: 'We allow extra time for Sintra moves and use vans suited to the access — switching to smaller vehicles for narrow forest tracks if needed. Loads are covered carefully against the famous Sintra mist. We\'ve moved customers in and out of Sintra estates, mountain villas, and Vila Velha apartments, and we know what each requires.',
      services: 'Estate and villa moves, family home removals, expat relocations, storage and inventory services.',
      keywords: 'removals Sintra, movers Sintra, Sintra moving company, Lisbon to Sintra removals, expat movers Sintra',
    },
    pt: {
      name: 'Sintra',
      title: 'Mudanças em Sintra',
      metaTitle: 'Mudanças e Transportes em Sintra | Removals Lisbon',
      metaDescription: 'Mudanças profissionais em Sintra. Mudamos famílias e profissionais entre Sintra e Lisboa, mais relocações dentro da serra de Sintra. Orçamento grátis.',
      intro: 'Sintra é o Portugal de conto de fadas — castelos, serra, neblina, e uma mistura de quintas históricas e moradias modernas. A combinação de estradas serpenteantes, ruas estreitas de vila e propriedades escondidas na floresta faz com que as mudanças aqui exijam sempre um plano cuidadoso.',
      challenges: [
        'Estradas serpenteantes acrescentam tempo de viagem e exigem condução cuidadosa',
        'Algumas propriedades só são acessíveis por caminhos florestais de uma via',
        'O tempo de Sintra (neblina, chuva) afeta o horário das cargas',
        'Os centros históricos das vilas têm acessos apertados',
      ],
      ourApproach: 'Damos tempo extra às mudanças em Sintra e usamos carrinhas adequadas ao acesso — mudando para veículos mais pequenos para caminhos florestais se necessário. As cargas são cobertas cuidadosamente contra a famosa neblina de Sintra. Já mudámos clientes em quintas, moradias na serra e apartamentos da Vila Velha, e sabemos o que cada um exige.',
      services: 'Mudanças de quintas e moradias, mudanças de casas familiares, relocações de expatriados, serviços de armazenamento e inventário.',
      keywords: 'mudanças Sintra, transportes Sintra, empresa mudanças Sintra, Lisboa para Sintra, mudanças expatriados Sintra',
    },
  },
  {
    slug: 'oeiras',
    region: 'greater',
    image: 'https://images.unsplash.com/photo-1568849676085-51415703900f?w=1600&q=80',
    en: {
      name: 'Oeiras',
      title: 'Removals in Oeiras',
      metaTitle: 'Removals & House Movers in Oeiras | Removals Lisbon',
      metaDescription: 'Reliable removal services for Oeiras and Carnaxide. Family relocations, corporate moves, and apartment removals along the Lisbon coast. Free quote.',
      intro: 'Oeiras is one of the most family-friendly municipalities in Greater Lisbon — modern apartment complexes, gated communities, and a high concentration of corporate offices and tech professionals. Moves here are typically straightforward but voluminous.',
      challenges: [
        'Gated communities require advance access coordination',
        'High-rise apartment blocks need lift-booking and protection',
        'Corporate moves often have tight weekend windows',
      ],
      ourApproach: 'We coordinate with building managers and security teams in advance to make sure access is smooth. For high-rise moves we book service lifts and protect them with padding. Corporate clients get evening and weekend slots so business operations aren\'t disrupted.',
      services: 'Family home and apartment moves, corporate relocations, IKEA and furniture delivery, storage solutions.',
      keywords: 'removals Oeiras, movers Oeiras, Oeiras moving company, corporate movers Oeiras, family movers Oeiras',
    },
    pt: {
      name: 'Oeiras',
      title: 'Mudanças em Oeiras',
      metaTitle: 'Mudanças e Transportes em Oeiras | Removals Lisbon',
      metaDescription: 'Serviços de mudanças fiáveis para Oeiras e Carnaxide. Relocações familiares, mudanças de empresas e mudanças de apartamento ao longo da costa de Lisboa.',
      intro: 'Oeiras é um dos concelhos mais amigos da família na Grande Lisboa — complexos modernos de apartamentos, condomínios fechados e uma alta concentração de escritórios e profissionais de tecnologia. As mudanças aqui são tipicamente simples mas volumosas.',
      challenges: [
        'Condomínios fechados exigem coordenação de acesso com antecedência',
        'Blocos de apartamentos altos exigem reserva de elevador e proteção',
        'Mudanças de empresas têm muitas vezes janelas apertadas ao fim de semana',
      ],
      ourApproach: 'Coordenamos com administradores de edifícios e equipas de segurança com antecedência para garantir um acesso fluido. Para mudanças em prédios altos reservamos os elevadores de serviço e protegemo-los com almofadagem. Clientes empresariais recebem horários noturnos e de fim de semana para que a atividade não seja perturbada.',
      services: 'Mudanças de casas familiares e apartamentos, relocações empresariais, entrega IKEA e mobiliário, soluções de armazenamento.',
      keywords: 'mudanças Oeiras, transportes Oeiras, empresa mudanças Oeiras, mudanças empresas Oeiras, mudanças famílias Oeiras',
    },
  },
  {
    slug: 'parque-das-nacoes',
    region: 'greater',
    image: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=1600&q=80',
    en: {
      name: 'Parque das Nações',
      title: 'Removals in Parque das Nações, Lisbon',
      metaTitle: 'Removals in Parque das Nações | Removals Lisbon',
      metaDescription: 'Professional removals for Parque das Nações, Lisbon. Modern high-rise apartments, expat moves, and corporate relocations. Free quote.',
      intro: 'Parque das Nações is Lisbon\'s most modern district — built for Expo \'98 and now home to high-rise apartments, expat families, and major corporate offices. Moves here are usually clean and straightforward, but high-rise logistics matter.',
      challenges: [
        'High-rise buildings with strict service-lift booking systems',
        'Concierge desks that require advance authorisation',
        'Underground parking with low ceilings',
        'Modern furniture often pre-assembled, requires careful disassembly',
      ],
      ourApproach: 'We handle the building admin in advance — booking lifts, registering the move, coordinating with security. Our team is experienced with the typical Parque das Nações furniture (lots of IKEA, lots of pre-assembled pieces) and we bring the right tools to disassemble and reassemble efficiently.',
      services: 'High-rise apartment removals, corporate relocations, IKEA disassembly and reassembly, expat moves.',
      keywords: 'removals Parque das Nações, movers Parque Nações Lisbon, expat movers Lisbon, high-rise movers Lisbon',
    },
    pt: {
      name: 'Parque das Nações',
      title: 'Mudanças no Parque das Nações, Lisboa',
      metaTitle: 'Mudanças no Parque das Nações | Removals Lisbon',
      metaDescription: 'Mudanças profissionais para o Parque das Nações, Lisboa. Apartamentos modernos em altura, mudanças de expatriados e relocações empresariais. Orçamento grátis.',
      intro: 'O Parque das Nações é o bairro mais moderno de Lisboa — construído para a Expo \'98 e hoje casa de apartamentos em altura, famílias expatriadas e grandes escritórios. As mudanças aqui são geralmente limpas e simples, mas a logística de torres altas é importante.',
      challenges: [
        'Edifícios em altura com sistemas rigorosos de reserva de elevador de serviço',
        'Receções com porteiro que exigem autorização prévia',
        'Estacionamento subterrâneo com tetos baixos',
        'Mobiliário moderno muitas vezes pré-montado, exige desmontagem cuidadosa',
      ],
      ourApproach: 'Tratamos da burocracia do edifício com antecedência — reserva de elevadores, registo da mudança, coordenação com a segurança. A nossa equipa tem experiência com o mobiliário típico do Parque das Nações (muito IKEA, muitas peças pré-montadas) e levamos as ferramentas certas para desmontar e remontar com eficiência.',
      services: 'Mudanças de apartamentos em altura, relocações empresariais, desmontagem e remontagem IKEA, mudanças de expatriados.',
      keywords: 'mudanças Parque das Nações, transportes Parque Nações Lisboa, mudanças expatriados Lisboa, mudanças torres Lisboa',
    },
  },
];

export function getNeighborhood(slug) {
  return neighborhoods.find((n) => n.slug === slug);
}
